End of 2024. Execution, fmod and fit parameters
JoseRuedaRueda/ScintSuite pull request #26
Opened 2024-12-28 15:44 UTC by alereyvinn

This is a first step to implement the new export format for strike maps.
Also some work has been done in the execution and forward modelling.

2025-01-27 15:01 UTC, linvelgal requested changes
@JoseRuedaRueda please review changes in _foward_modelling.py

2025-01-27 15:01 UTC, linvelgal commented on ScintSuite/SimulationCodes/SINPA/_forward_modelling.py
> +    Transfors the pitch-gyroradius signal space to pitch-energy signal
signal space?

2025-01-27 16:47 UTC, JoseRuedaRueda commented
Sorry I was on Holidays when this came out and until today that I got notified again because of Lina's comments I did not realised this was pending.

This can't be approved, one can't extrapolate the resolutions to points without ions in the grid. Please correct all the comments an reopen the merge request

2025-01-28 17:11 UTC, JoseRuedaRueda commented
Aja, sorry, I did all the comment but it seems I forgot to click 'submit review' so you only saw Lina's comments... My bad!

2025-01-29 09:25 UTC, alereyvinn commented on ScintSuite/_StrikeMap/_FILD_StrikeMap.py
> +                            .interpolate_na(dim='y', fill_value='extrapolate')
My idea was to be able to generate a database with the same coordinates for the different parameters of the resolutions, fits, and the WF. So everything is in the same array, which makes it easier to work with and export. In any case I modify the _resolutions parameters, this is just a wrap of all the things.

Here I'm interpolating the fit parameters to the WF, but I never compute the WF again, since is the last thing I add to the dataset. And the WF is not computed with the values in the dataset, but with those in _resolutions.

Not having NaN makes it easier/nicer for some plots. Obviously we shouldn't use this to compute a new WF. But I can remove this no problem.

2025-01-29 17:39 UTC, JoseRuedaRueda commented on ScintSuite/_StrikeMap/_FILD_StrikeMap.py
> +                            .interpolate_na(dim='y', fill_value='extrapolate')
But that is even more prone to disaster. If someone get that database, they will us the parameters inside, so they will calculate things thinking FILD measure in those areas. Which can have disastrous consequences (from bad interpretation of experimental data to million of dollars wasted in a FILD which does not measure as expected) 

If you need something for plottinng, you can easily flag that NaN in the matrix and convert them to zeros just for the plot

2025-01-29 17:39 UTC, JoseRuedaRueda commented
Please reopen the merge and answer all comments so I can merge it :)

2025-01-30 09:21 UTC, alereyvinn commented on ScintSuite/SimulationCodes/Common/geometry.py
> +def scint_ConvexHull(scint):
Should work, yes. I'll check it. The think is that in this case we are only interested in the two coordinates perpendicular to the optix axis, since its a 2D image.

2025-01-31 19:14 UTC, alereyvinn commented on ScintSuite/SimulationCodes/SINPA/_forward_modelling.py
>  def synthetic_signal_pr(distro, WF = None, gyrophases = np.pi,
Done

2025-01-31 19:15 UTC, alereyvinn commented on ScintSuite/_StrikeMap/_FILD_StrikeMap.py
> +                uniformity between matrices
Solved

2025-01-31 19:19 UTC, alereyvinn commented on ScintSuite/LibData/AUG/Misc.py
> +        if channels == 'all':
Don't understand. This is just a flag that is you say 'all', load all channels. I don't get what you mean by None

2025-01-31 19:21 UTC, alereyvinn commented on ScintSuite/_StrikeMap/_FILD_StrikeMap.py
> +        param  self_complete: fills the nan values of the matrices
not an option anymore

2025-01-31 19:24 UTC, JoseRuedaRueda requested changes

2025-01-31 19:24 UTC, JoseRuedaRueda commented on ScintSuite/LibData/AUG/Misc.py
> +        if channels == 'all':
channels is usually and Array of numbers, if you make the check whether if it is 'all' you gave the option for being an str, which is confusing for users / problematic for the IDE which gives automatic code completion / help

If you make the comparison with None, will be better, as None has no datatype and is the python joker for the case where the user does not provide a given argument

2025-02-03 16:18 UTC, alereyvinn commented on ScintSuite/SimulationCodes/Common/geometry.py
> +    xdum = scint._coord_pix['x']
Done

2025-02-06 16:53 UTC, JoseRuedaRueda commented on ScintSuite/_StrikeMap/_FILD_StrikeMap.py
> +            self._resolutions['fit_xarrays']['WF'] = self.instrument_function
I was going to merge this but this is weird to me:
1- you should not interpolate. Yes, is easier for database or whatever but it is really important that in the strike map, only the values from the FILDSIM simulations are launched, any interpolated value should be present, as they could differ depending on the interpolation method or the grid. Please remove this and apply the interpolation in your personal script where you do things with the exported data
2- do not copy the WF. Python some times makes copies, some times references, the WF can be up to 100Gb depending on the grid, line 498 could imply to duplicate the mamory use of this 100Gb for no readon, whenever you export the resolutions['fit_xarray'], put a line below and then export the WF. if you want them in the same file, you can create a tar file or merge the two h5 output files.

2025-02-06 17:15 UTC, JoseRuedaRueda approved these changes

2025-02-06 17:16 UTC, merged